# Default values for kubernetes-replicator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: asia.gcr.io/olli-iviet/kubernetes-replicator
  tag: 2.0.23
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

previewNSPrefix: jx-olli-ai-kubernetes-replicator

nodeSelector: {}

tolerations: []

affinity: {}
